### ISSUE TITLE
Check your internet toast issue

### ISSUE THREAD

**Issue by waqarnaik** [NikhilBhople/InAppYouTubeChannelSubscribe#1]
Bro when I Successfully change the Google services json file & the youtube api key + I have also properly add all dependency as your project as but & also setup the firebase authentication but after running the app after clicking on the gmail account in list it shows toast "check your internet"

**Comment by NikhilBhople** [comment]
Ok, a message may be wrong but your problem seems to be with Google authentication with you. Kindly check your GoogleServices.json file
